// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: GPL-3.0-or-later

= How to Build

== Prerequisites

.To build *favico*, you will need the following dependencies
* https://doc.rust-lang.org/stable/cargo/[Cargo] (v1.74.0 or later)

.To build a man page, you will need the following additional dependencies
* https://asciidoctor.org/[Asciidoctor]

== Building from source

.To clone the repository
[source,sh]
----
git clone https://github.com/sorairolake/favico.git
cd favico
----

.To build a package
[source,sh]
----
just build
----

.To find the directory where a man page are generated
[source,sh]
----
fd -t directory out ./target/*/build/favico-*
----

== Crate features

`dds`::

  Enable generating from the DDS image. This is enabled by default.

`ff`::

  Enable generating from the Farbfeld image. This is enabled by default.

`gif`::

  Enable generating from the GIF image. This is enabled by default.

`hdr`::

  Enable generating from the Radiance RGBE image. This is enabled by default.

`jpeg`::

  Enable generating from the JPEG image. This is enabled by default.

`exr`::

  Enable generating from the OpenEXR image. This is enabled by default.

`pnm`::

  Enable generating from the PNM image. This is enabled by default.

`qoi`::

  Enable generating from the QOI image. This is enabled by default.

`tga`::

  Enable generating from the TGA image. This is enabled by default.

`tiff`::

  Enable generating from the TIFF image. This is enabled by default.

`webp`::

  Enable generating from the WebP image. This is enabled by default.

`xbm`::

  Enable generating from the XBM image. This is enabled by default.
