# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "favico"
version = "0.1.1"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2021"
rust-version = "1.74.0"
description = "An utility for creating favicons"
readme = "README.md"
homepage = "https://sorairolake.github.io/favico/"
repository = "https://github.com/sorairolake/favico"
license = "GPL-3.0-or-later"
keywords = ["favicon", "icon"]
categories = ["command-line-utilities"]
include = ["/LICENSES", "/README.md", "/src"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
bat = { version = "0.24.0", default-features = false, features = ["regex-fancy"] }
clap = { version = "4.5.4", features = ["derive", "wrap_help"] }
clap_complete = "4.5.1"
clap_complete_nushell = "4.5.1"
csscolorparser = "0.6.2"
image = "0.25.1"
indicatif = "0.17.8"
serde_json = { version = "1.0.115", features = ["preserve_order"] }
sysexits = "0.7.12"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
tempfile = "3.10.1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
