// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= favico(1)
// Specify in UTC.
:docdate: 2024-04-15
:doctype: manpage
ifdef::revnumber[:mansource: favico {revnumber}]
ifndef::revnumber[:mansource: favico]
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

favico - an utility for creating favicons

== SYNOPSIS

*{manname}* [_OPTION_]... [_IMAGE_]

== DESCRIPTION

*{manname}* is a command-line utility for creating favicons.

== POSITIONAL ARGUMENTS

_IMAGE_::

  Input image file. If _IMAGE_ is not specified, or if "-" is specified, the
  image will be read from stdin. Supported raster image formats are based on
  the formats supported by the image crate. The format of _IMAGE_ is determined
  based on the extension or the magic number if possible. If the format cannot
  be determined, use *--format*. Note that _IMAGE_ must be square.

== OPTIONS

*-o*, *--output* _PATH_::

  Directory to output generated files. If the directory does not exist, it will
  be created. Default is the current directory.

*--png*::

  Store PNG images instead of BMP images to an ICO image.

*--name* _NAME_::

  Set the name member of the web app manifest.

*--short-name* _NAME_::

  Set the short_name member of the web app manifest. If _NAME_ is not
  specified, the name specified in *--name* will be set.

*--theme-color* _COLOR_::

  Set the theme_color member of the web app manifest. _COLOR_ takes a CSS color
  string. Default is "#ffffff".

*--background-color* _COLOR_::

  Set the background_color member of the web app manifest. _COLOR_ takes a CSS
  color string. Default is "#ffffff".

*--filter* _FILTER_::

  Sampling filter used to resize the input image.

  The possible values are:{blank}:::

    *nearest*::::

      Nearest Neighbor.

    *triangle*::::

      Linear Filter.

    *catmullrom*::::

      Cubic Filter. This is the default value.

    *gaussian*::::

      Gaussian Filter.

    *lanczos3*::::

      Lanczos with window 3.

*-f*, *--format* _FORMAT_::

  The format of the input. If _FORMAT_ is not specified, the format is
  determined based on the extension or the magic number.

  The possible values are:{blank}:::

    *bmp*::::

      Windows Bitmap.

ifdef::dds,env-github,site-gen-antora[]
    *dds*::::

      DirectDraw Surface.
endif::[]

ifdef::ff,env-github,site-gen-antora[]
    *farbfeld*::::

      Farbfeld.
endif::[]

ifdef::gif,env-github,site-gen-antora[]
    *gif*::::

      Graphics Interchange Format.
endif::[]

ifdef::hdr,env-github,site-gen-antora[]
    *hdr*::::

      Radiance RGBE.
endif::[]

    *ico*::::

      ICO file format. This value also includes the CUR file format.

ifdef::jpeg,env-github,site-gen-antora[]
    *jpeg*::::

      JPEG.
endif::[]

ifdef::exr,env-github,site-gen-antora[]
    *openexr*::::

      OpenEXR.
endif::[]

    *png*::::

      Portable Network Graphics.

ifdef::pnm,env-github,site-gen-antora[]
    *pnm*::::

      Portable Anymap Format.
endif::[]

ifdef::qoi,env-github,site-gen-antora[]
    *qoi*::::

      Quite OK Image Format.
endif::[]

ifdef::tga,env-github,site-gen-antora[]
    *tga*::::

      Truevision TGA.
endif::[]

ifdef::tiff,env-github,site-gen-antora[]
    *tiff*::::

      Tag Image File Format.
endif::[]

ifdef::webp,env-github,site-gen-antora[]
    *webp*::::

      WebP.
endif::[]

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

*--generate-completion* _SHELL_::

  Generate shell completion. The completion is output to stdout.

  The possible values are:{blank}:::

    *bash*::::

      Bash.

    *elvish*::::

      Elvish.

    *fish*::::

      fish.

    *nushell*::::

      Nushell.

    *powershell*::::

      PowerShell.

    *zsh*::::

      Zsh.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

== NOTES

Source repository:{blank}::

  https://github.com/sorairolake/favico

image crate:{blank}::

  https://crates.io/crates/image

Web App Manifest:{blank}::

  https://developer.mozilla.org/en-US/docs/Web/Manifest

CSS Color Module Level 4:{blank}::

  https://www.w3.org/TR/css-color-4/

== EXAMPLES

Generate favicons in the current directory:{blank}::

  $ *favico input.png*

Generate favicons in the specified directory:{blank}::

  $ *favico -o out input.png*

Generate favicons with the specified member:{blank}::

  $ *favico --name app --theme-color "#a52a2a" input.png*

Generate favicons with the specified sampling filter:{blank}::

  $ *favico --filter nearest input.png*

Generate favicons from a WebP image:{blank}::

  $ *favico -f webp input.webp*

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*magick*(1)
