// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= favico(1)
// Specify in UTC.
:docdate: 2025-03-10
:revnumber: 0.1.9
:doctype: manpage
:mansource: favico {revnumber}
:manmanual: General Commands Manual
:enwp-url: https://en.wikipedia.org
:enwp-article-url: {enwp-url}/wiki
:png-url: {enwp-article-url}/PNG
:ico-url: {enwp-article-url}/ICO_(file_format)
:bmp-url: {enwp-article-url}/BMP_file_format
:mdn-url: https://developer.mozilla.org
:mdn-refs-url: {mdn-url}/en-US/docs/Web
:web-app-manifest-url: {mdn-refs-url}/Manifest
:pwa-url: {mdn-refs-url}/Progressive_web_apps
:dds-url: {enwp-article-url}/DirectDraw_Surface
:farbfeld-url: https://tools.suckless.org/farbfeld/
:gif-url: {enwp-article-url}/GIF
:radiance-rgbe-url: {enwp-article-url}/RGBE_image_format
:jpeg-url: https://jpeg.org/jpeg/
:openexr-url: https://openexr.com/
:pnm-url: https://netpbm.sourceforge.net/doc/pnm.html
:qoi-url: https://qoiformat.org/
:tga-url: {enwp-article-url}/Truevision_TGA
:tiff-url: {enwp-article-url}/TIFF
:webp-url: https://developers.google.com/speed/webp/
:xbm-url: {enwp-article-url}/X_BitMap
:image-crates-url: https://crates.io/crates/image
:css-color-url: https://www.w3.org/TR/css-color-4/
:sysexits-man-page-url: https://man.openbsd.org/sysexits
:repo-url: https://github.com/sorairolake/favico

== NAME

favico - an utility for creating favicons

== SYNOPSIS

*{manname}* [_OPTION_]... [_IMAGE_]

== DESCRIPTION

*{manname}* is a command-line utility for creating favicons.

*{manname}* will generate favicons in the {png-url}[PNG] format and the
{ico-url}[ICO] format which contains images in the {bmp-url}[BMP] format or the
PNG format from the input image file, and outputs them to the specified
directory or the current directory. *{manname}* also generates the
{web-app-manifest-url}[web app manifest] for a {pwa-url}[progressive web app]
(PWA) in the same directory where the favicons are output.

.List of the generated files
|===
|Filename |Description

|`android-chrome-192x192.png`
|For Android Chrome

|`android-chrome-512x512.png`
|For Android Chrome

|`apple-touch-icon.png`
|For Safari on iOS and iPadOS

|`favicon-16x16.png`
|The classic favicon

|`favicon-32x32.png`
|For Safari on macOS

|`favicon.ico`
|The original favicon

|`site.webmanifest`
|Web app manifest
|===

Some members of the web app manifest can be configured via options.

.List of the configurable members
* `name` (*--name*)
* `short_name` (*--short-name*)
* `theme_color` (*--theme-color*)
* `background_color` (*--background-color*)

The {css-color-url}[CSS color string] can be specified as a value for
*--theme-color* and/or *--background-color*.

.List of methods to specify a color
|===
|Format |Examples

|Named colors
|`brown`, `lightslategray`

|Hexadecimal notations
|`#111`, `#eee8`, `#a52a2a`, `#7788997f`

|RGB functions
|`rgb(165 42 42)`, `rgb(119 136 153 / 49.8%)`

|HSL functions
|`hsl(248 39% 39.2%)`, `hsl(0 0% 66.3% / 49.8%)`

|HWB function
|`hwb(50.6 0% 0%)`, `hwb(0 66.3% 33.7% / 49.8%)`

|Oklab function
|`oklab(50.4% -0.0906 0.0069)`, `oklab(61.9% -0.0120 -0.0302 / 0.5)`

|Oklch function
|`oklch(59.41% 0.16 301.29)`, `oklch(61.9% 0.032 248.35 / 49.8%)`
|===

.Supported input image file formats
* {bmp-url}[BMP]
* {dds-url}[DDS] (if enabled at compile time)
* {farbfeld-url}[Farbfeld] (if enabled at compile time)
* {gif-url}[GIF] (if enabled at compile time)
* {radiance-rgbe-url}[Radiance RGBE] (if enabled at compile time)
* {ico-url}[ICO]
* {jpeg-url}[JPEG] (if enabled at compile time)
* {openexr-url}[OpenEXR] (if enabled at compile time)
* {png-url}[PNG]
* {pnm-url}[PNM] (if enabled at compile time)
* {qoi-url}[QOI] (if enabled at compile time)
* {tga-url}[TGA] (if enabled at compile time)
* {tiff-url}[TIFF] (if enabled at compile time)
* {webp-url}[WebP] (if enabled at compile time)
* {xbm-url}[XBM] (if enabled at compile time)

Use *-t* option to specify the image format. If this option is not specified,
the image format is determined based on the extension or the magic number.

== POSITIONAL ARGUMENTS

_IMAGE_::

  Input image file. If _IMAGE_ is not specified, or if "-" is specified, the
  image will be read from standard input. Supported raster image formats are
  based on the formats supported by the {image-crates-url}[`image`] crate. The
  format of _IMAGE_ is determined based on the extension or the magic number if
  possible. If the format cannot be determined, use *--format*. Note that
  _IMAGE_ must be square.

== OPTIONS

*-o*, *--output* _PATH_::

  Directory to output generated files. If the directory does not exist, it will
  be created. Default is the current directory.

*--png*::

  Store PNG images instead of BMP images to an ICO image.

*--name* _NAME_::

  Set the name member of the web app manifest.

*--short-name* _NAME_::

  Set the short_name member of the web app manifest. If _NAME_ is not
  specified, the name specified in *--name* will be set.

*--theme-color* _COLOR_::

  Set the theme_color member of the web app manifest. _COLOR_ takes a
  {css-color-url}[CSS color string]. Note that _COLOR_ is converted to the sRGB
  color space, so a lossy conversion may be performed. Default is "#ffffff".

*--background-color* _COLOR_::

  Set the background_color member of the web app manifest. _COLOR_ takes a CSS
  color string. Note that _COLOR_ is converted to the sRGB color space, so a
  lossy conversion may be performed. Default is "#ffffff".

*--filter* _FILTER_::

  Sampling filter used to resize the input image.

  The possible values are:{blank}:::

    *nearest*::::

      Nearest Neighbor.

    *triangle*::::

      Linear Filter.

    *catmullrom*::::

      Cubic Filter. This is the default value.

    *gaussian*::::

      Gaussian Filter.

    *lanczos3*::::

      Lanczos with window 3.

*-f*, *--format* _FORMAT_::

  The format of the input. If _FORMAT_ is not specified, the format is
  determined based on the extension or the magic number.

  The possible values are:{blank}:::

    *bmp*::::

      Windows Bitmap.

    *dds*::::

      DirectDraw Surface. This value is available if the `dds` feature is
      enabled at compile time.

    *farbfeld*::::

      Farbfeld. This value is available if the `ff` feature is enabled at
      compile time.

    *gif*::::

      Graphics Interchange Format. This value is available if the `gif` feature
      is enabled at compile time.

    *hdr*::::

      Radiance RGBE. This value is available if the `hdr` feature is enabled at
      compile time.

    *ico*::::

      ICO file format.

    *jpeg*::::

      JPEG. This value is available if the `jpeg` feature is enabled at compile
      time.

    *openexr*::::

      OpenEXR. This value is available if the `exr` feature is enabled at
      compile time.

    *png*::::

      Portable Network Graphics.

    *pnm*::::

      Portable Anymap Format. This value is available if the `pnm` feature is
      enabled at compile time.

    *qoi*::::

      Quite OK Image Format. This value is available if the `qoi` feature is
      enabled at compile time.

    *tga*::::

      Truevision TGA. This value is available if the `tga` feature is enabled
      at compile time.

    *tiff*::::

      Tag Image File Format. This value is available if the `tiff` feature is
      enabled at compile time.

    *webp*::::

      WebP. This value is available if the `webp` feature is enabled at compile
      time.

    *xbm*::::

      X BitMap. This value is available if the `xbm` feature is enabled at
      compile time.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

*--generate-completion* _SHELL_::

  Generate shell completion. The completion is output to standard output.

  The possible values are:{blank}:::

    *bash*::::

      Bash.

    *elvish*::::

      Elvish.

    *fish*::::

      fish.

    *nushell*::::

      Nushell.

    *powershell*::::

      PowerShell.

    *zsh*::::

      Zsh.

== EXIT STATUS

*0*::

  Successful program execution.

*1*::

  An error occurred.

*2*::

  An error occurred while parsing command-line arguments.

Exit statuses other than these are defined by
{sysexits-man-page-url}[`<sysexits.h>`].

== NOTES

Source repository:{blank}::

  {repo-url}

== EXAMPLES

Generate favicons in the current directory:{blank}::

  $ *favico input.png*

Generate favicons in the specified directory:{blank}::

  $ *favico -o out input.png*

Generate favicons with the specified member:{blank}::

  $ *favico --name app --theme-color "#a52a2a" input.png*

Generate favicons with the specified sampling filter:{blank}::

  $ *favico --filter nearest input.png*

Generate favicons from a WebP image:{blank}::

  $ *favico -f webp input.webp*

== REPORTING BUGS

Report bugs to:{blank}::

  {repo-url}/issues

== COPYRIGHT

Copyright (C) 2024 Shun Sakai

. This program is distributed under the terms of the GNU General Public License
  v3.0 or later.
. This manual page is distributed under the terms of the Creative Commons
  Attribution 4.0 International Public License.

This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.

== SEE ALSO

*magick*(1)
